server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Sairaj@15
    url: jdbc:mysql://localhost:3306/sbms
    username: sairaj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
